apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gpu-operator
  namespace: gpu-operator
spec:
  interval: 30m
  chart:
    spec:
      chart: gpu-operator
      version: "v24.9.0"
      sourceRef:
        kind: HelmRepository
        name: nvidia
  values:
    driver:
      enabled: false # EKS GPU AMI pre-installs drivers
    toolkit:
      enabled: true
    dcgmExporter:
      enabled: true
      serviceMonitor:
        enabled: true
    operator:
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
    nfd:
      master:
        tolerations:
          - key: nvidia.com/gpu
            operator: Exists
            effect: NoSchedule
      gc:
        tolerations:
          - key: nvidia.com/gpu
            operator: Exists
            effect: NoSchedule
